language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
    - "backend/node_modules"
    - "frontend/node_modules"
script: npm run test
before_deploy: npm i now --no-save
deploy:
  provider: script
  script: now --token $NOW_TOKEN --public && now --token $NOW_TOKEN alias && now --token $NOW_TOKEN rm foxandsheep --safe --yes
  skip_cleanup: true
  on:
    master: true